FROM python:3.12-slim
#Instrucciones para crear una imagen para el contenedor
#crar carpeta de trabajo
WORKDIR /app

#Copia de los requerimientos 
COPY requirements.txt .

#instalados 
RUN pip install --no-cache-dir -r requirements.txt 

#Copiar el codigo del proyecto ---origen ---contenedor
COPY ./app ./app

#Exponar el puerto
EXPOSE 5010

#Comandos para ejecutar FASTAPI
CMD ["uvicorn","app.main:app","--host","0.0.0.0","--port","5010","--reload"]